### PR TITLE
runtime-v2:  repositoryrefresh task

### PR DESCRIPTION
**Pull request by amithkb**
runtime-v2 compatibility repository refresh task with integration test

### CODE REVIEW

**Comment by ibodrov** [comment]
Do we really need to keep the v1 version? @brig wdyt?
I think we can just replace the current task with its v2 version. Even if the request is handled by an older version of the Agent - the input parameter format is still the same, so it'll just work, right?

**Comment by brig** [comment]
> Do we really need to keep the v1 version? @brig wdyt?
> I think we can just replace the current task with its v2 version. Even if the request is handled by an older version of the Agent - the input parameter format is still the same, so it'll just work, right?

yep. we need to update [`concord.yml`](https://github.com/walmartlabs/concord/blob/master/server/impl/src/main/resources/com/walmartlabs/concord/server/org/triggers/concord.yml) runtime to v2 and we can remove/replace v1 version of task

**Comment by ibodrov** [comment]
Can we do that in the same PR? @brig @amithkb ?

**Comment by amithkb** [comment]
> Can we do that in the same PR? @brig @amithkb ?

sure. will update

**Comment by amithkb** [comment]
``` 
21:16:02 [INFO ] Using entry point: default
21:16:02 [INFO ] Enqueued. Waiting for an agent (requirements=null)...
21:16:02 [INFO ] Acquired by: Concord-Agent: id=68104519-0d53-4291-ade7-981b6ac4eddd
21:16:02 [INFO ] Downloading the process state...
21:16:02 [INFO ] Process state download took 11ms
21:16:02 [INFO ] Runtime: concord-v1
21:16:02 [INFO ] Resolving process dependencies...
21:16:04 [INFO ] Dependencies: 
	mvn://com.walmartlabs.concord.plugins.basic:concord-tasks:1.66.1-SNAPSHOT
	mvn://com.walmartlabs.concord.plugins.basic:slack-tasks:1.66.1-SNAPSHOT
	mvn://com.walmartlabs.concord.plugins.basic:http-tasks:1.66.1-SNAPSHOT
21:16:08 [INFO ] Process status: RUNNING
21:16:09 [WARN ] eval ['${repositoryRefresh}'] -> error: ELResolver cannot handle a null base Object with identifier 'repositoryRefresh'
21:16:09 [ERROR] main -> unhandled exception
javax.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier 'repositoryRefresh'
	at io.takari.bpm.el.DefaultExpressionManager.eval(DefaultExpressionManager.java:52) [3 skipped]
	at io.takari.bpm.context.ExecutionContextImpl.eval(ExecutionContextImpl.java:42)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:128)
	at io.takari.bpm.reducers.ExpressionsReducer$DelegateFn.call(ExpressionsReducer.java:1)
	at io.takari.bpm.reducers.ExpressionsReducer.reduce(ExpressionsReducer.java:66)
	at io.takari.bpm.reducers.CombiningReducer.reduce(CombiningReducer.java:18)
	at io.takari.bpm.DefaultExecutor.eval(DefaultExecutor.java:61)
	at io.takari.bpm.AbstractEngine.runLockSafe(AbstractEngine.java:209)
	at io.takari.bpm.AbstractEngine.start(AbstractEngine.java:69)
	at com.walmartlabs.concord.runner.Main.start(Main.java:272)
	at com.walmartlabs.concord.runner.Main.executeProcess(Main.java:172)
	at com.walmartlabs.concord.runner.Main.run(Main.java:144)
	at com.walmartlabs.concord.runner.Main.main(Main.java:486)
21:16:10 [ERROR] Process exit code: 1
21:16:10 [INFO ] Process status: FAILED
```

The above error appears when we remove v1 task and use following concord yml to test. So anything is missing here or updating configuration to runtime-v2 is mandatory in concord.yml?

```
flows:
  default:
    - task: repositoryRefresh
      in:
        repositoryInfo:
          - repositoryId: "b31b0b06-c33c-11e7-b0e9-8702fc03629f"
            repository: "triggers"
    - log: "Done!"
```

**Comment by ibodrov** [comment]
Works fine for me: 
image

Make sure your Agent is not picking up older JARs.

**Comment by amithkb** [comment]
Got it. Repository refresh on event trigger(say repository created/updated which based on [concord.yml](https://github.com/walmartlabs/concord/blob/master/server/impl/src/main/resources/com/walmartlabs/concord/server/org/triggers/concord.yml)) will work. And using repository refresh as a standalone task will default to runtime-v1 and won't work correct?

**Comment by ibodrov** [comment]
> And using repository refresh as a standalone task will default to runtime-v1 and won't work correct?
Correct, it won't be available for processes that are not using `runtime: concord-v2`.
Which is fine, we're not expecting this task to be called by users anyway, it's purely internal business of how Concord processes GH pushes.

**Comment by amithkb** [comment]
anything yet to be implemented for this PR @ibodrov  @brig ?

**Review by brig — APPROVED** [review]

**Pull request merged**
