### PR TITLE
fix iteritems to items for py2-py3 compatibility

### PR DESCRIPTION
**Pull request by jchikatur**
fix `iteritems` to `items` for py2-py3 compatibility

### CODE REVIEW

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by mtkunkel** [comment]
Looks good to me.  Curious what's `concord-ci.ibodrov.ca` has to say .  Python3 changes to the Dockerfiles coming in a follow-on PR.

**Review by mtkunkel — APPROVED** [review]

**Review by benbroadaway — APPROVED** [review]

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by ibodrov** [comment]
> Looks good to me. Curious what `concord-ci.ibodrov.ca` has to say . Python3 changes to the Dockerfiles coming in a follow-on PR.

Looking into it...

**Comment by mtkunkel** [comment]
@jchikatur Sent more details in slack:

```17:02:54 ANSIBLE: match_task_args: [{'values': ['.*secret.*'], 'name': 'src'}] on {'src': 'super-secret-file.dat', 'dest': '/tmp/my.ini'}
17:02:54 ANSIBLE: The full traceback is:
17:02:54 ANSIBLE: Traceback (most recent call last):
17:02:54 ANSIBLE:   File "/usr/local/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 145, in run
17:02:54 ANSIBLE:     res = self._execute()
17:02:54 ANSIBLE:   File "/tmp/concord/prefork5165077895217841304/payload/.concord_tmp/ansible1643878984233725670/_callbacks/concord_task_executor_patch.py", line 107, in _execute
17:02:54 ANSIBLE:     if taskPolicy.is_deny(_task):
17:02:54 ANSIBLE:   File "/tmp/concord/prefork5165077895217841304/payload/.concord_tmp/ansible1643878984233725670/_python_lib/task_policy.py", line 47, in is_deny
17:02:54 ANSIBLE:     if self._match_ansible_rule(r, action, args):
17:02:54 ANSIBLE:   File "/tmp/concord/prefork5165077895217841304/payload/.concord_tmp/ansible1643878984233725670/_python_lib/task_policy.py", line 78, in _match_ansible_rule
17:02:54 ANSIBLE:     if 'params' in rule and not self._match_task_args(rule['params'], task_args):
17:02:54 ANSIBLE:   File "/tmp/concord/prefork5165077895217841304/payload/.concord_tmp/ansible1643878984233725670/_python_lib/task_policy.py", line 88, in _match_task_args
17:02:54 ANSIBLE:     for ta_name, ta_value in task_args.iteritems():
17:02:54 ANSIBLE: AttributeError: 'dict' object has no attribute 'iteritems'
17:02:54 ANSIBLE: 
17:02:54 ANSIBLE: fatal: [127.0.0.1]: FAILED! => {
17:02:54 ANSIBLE:     "msg": "Unexpected failure during module execution.",
17:02:54 ANSIBLE:     "stdout": ""
17:02:54 ANSIBLE: }```

**Pull request merged**
