### PR TITLE
dependency-mananager: add support for preemptive basic auth

### PR DESCRIPTION
**Pull request by ibodrov**
Example mvn.json:
```json
{
  "repositories": [
    {
      "id": "host",
      "url": "https://my-bucket.s3.us-west-2.amazonaws.com/maven",
      "auth": {
        "username": "user",
        "password": "pwd",
        "preemptiveAuth": "true"
      }
    }
  ]
}
```

### CODE REVIEW

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by ibodrov** [comment]
@concord-ci test it

**Review by brig — DISMISSED** [review]

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by brig** [comment]
docs: https://github.com/walmartlabs/concord-website/pull/89

**Pull request merged**
