### PR TITLE
serialVersionUID up

### PR DESCRIPTION
**Pull request by brig**

### CODE REVIEW

**Comment by brig** [comment]
@concord-ci test it

**Comment by brig** [comment]
@concord-ci test it

**Comment by benbroadaway** [comment]
Is this going to affect serialized variables stored in `process_state` between versions if a process suspends before the upgrade and resumes afterwards?

**Comment by brig** [comment]
> Is this going to affect serialized variables stored in `process_state` between versions if a process suspends before the upgrade and resumes afterwards?

shouldn't, I hope :)
all missing `serialVersionUID` are specified for classes that used in serialization of process state. for example: https://github.com/walmartlabs/concord/pull/537/files#diff-314bd592f1352a5ff4aec42725b7652363f7023ccb024c42e37dc63ebc8dcfa4R34

these changes will help not to affect the processes when switching from Java 8 to Java 11+

**Review by ibodrov — APPROVED** [review]

**Pull request merged**
