### PR TITLE
concord-server: update jOOQ to 3.14.0

### PR DESCRIPTION
**Pull request by ibodrov**
In jOOQ 3.14.0 `DSLContext` is no longer `AutoCloseable` (see
https://github.com/jOOQ/jOOQ/issues/10512).

Normally, explicit management of `DSLContext` objects is required only
when it is used without a connection pool. Which is not applicable to
the Concord's case.

### CODE REVIEW

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by benbroadaway** [comment]
@ibodrov is this still WIP?

**Comment by ibodrov** [comment]
> @ibodrov is this still WIP?

Yes, see the TODO above.

**Comment by ibodrov** [comment]
The fact that it passes the tests doesn't look too good haha

**Comment by ibodrov** [comment]
Now it is done.

**Review by benbroadaway — APPROVED** [review]

**Pull request merged**
