### PR TITLE
Compiled Bug Fixes from Muse Bug Bash

### PR DESCRIPTION
**Pull request by nescohen**
This merge request is a collection of crowd-sourced bug fixes from the Muse Bug Bash ran as a contest at the DevOps Enterprise Summit in cooperation with Bryan Finster at Walmart Labs. We’ve compiled the results into this PR. 

Going forward, if you want Muse to automatically analyze code at each Pull Request and deliver results as comments in code review, you can install our Github App https://github.com/marketplace/muse-dev and it will always be free for open source projects. We’d be happy to chat if you’d like to learn more, or feel free to install it on your project via Github.

### CODE REVIEW

**Comment by ibodrov** [comment]
FYI, tests can only run from branches, repository forks are not supported.

**Comment by nescohen** [comment]
> FYI, tests can only run from branches, repository forks are not supported.

Sorry I didn't realize this. Is there a better way to submit a PR to concord. Usually I don't have permission to create a new branch.

**Comment by nescohen** [comment]
@ibodrov 
I tried to push it to a new branch, but I got permission denied. Is there a path to being added as a collaborator? Or any other documentation you can point me to? 
Thanks!

**Comment by nescohen** [comment]
@ibodrov Hey any updates on this? I'd be happy to help in any way.

**Comment by mtkunkel** [comment]
Please split this PR into smaller, targeted requests for each type of issue. Some great PR's would be:
- Secure Cookies
- Explicit Encoding
- .execute() overrides

As it exists today, the PR has broken unit tests:
 `./mvnw clean install` 

```java.lang.UnsupportedOperationExceptionat
java.util.Collections$UnmodifiableMap.remove(Collections.java:1462)at
com.walmartlabs.concord.project.yaml.YamlFormConverter.convert(YamlFormConverter.java:84)at
com.walmartlabs.concord.project.yaml.YamlFormConverter.convert(YamlFormConverter.java:79)at
com.walmartlabs.concord.project.yaml.YamlFormConverter.convert(YamlFormConverter.java:69)at
com.walmartlabs.concord.project.yaml.YamlFormConverter.convert(YamlFormConverter.java:75)at
com.walmartlabs.concord.project.ProjectLoader$ProjectDefinitionBuilder.loadDefinitions(ProjectLoader.java:284)at
com.walmartlabs.concord.project.ProjectLoader$ProjectDefinitionBuilder.loadDefinitions(ProjectLoader.java:258)at
com.walmartlabs.concord.project.ProjectLoader$ProjectDefinitionBuilder.access$4(ProjectLoader.java:256)at
com.walmartlabs.concord.project.ProjectLoader.loadProject(ProjectLoader.java:64)at
com.walmartlabs.concord.project.yaml.AbstractYamlParserTest$TestWorkflowProvider.loadWorkflow(AbstractYamlParserTest.java:198```

**Pull request closed without merging**
