### PR TITLE
http-plugin: add support for custom truststore

### PR DESCRIPTION
**Pull request by amithkb**
* Add `strictSsl` option
* Add support for `custom truststore`

### CODE REVIEW

**Comment by amithkb** [comment]
@concord-ci test it

**Comment by amithkb** [comment]
@concord-ci test it

**Comment by ibodrov** [comment]
@amithkb it failed with
```
12:22:51 [INFO ] [ERROR] Tests run: 73, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 17.405 s <<< FAILURE! - in TestSuite
12:22:51 [INFO ] [ERROR] testParallelOut on testParallelOut(com.walmartlabs.concord.runtime.v2.runner.MainTest)(com.walmartlabs.concord.runtime.v2.runner.MainTest)  Time elapsed: 0.091 s  <<< FAILURE!
12:22:51 [INFO ] java.util.ConcurrentModificationException
12:22:51 [INFO ] 	at com.walmartlabs.concord.runtime.v2.runner.MainTest.run(MainTest.java:1006)
12:22:51 [INFO ] 	at com.walmartlabs.concord.runtime.v2.runner.MainTest.run(MainTest.java:966)
12:22:51 [INFO ] 	at com.walmartlabs.concord.runtime.v2.runner.MainTest.testParallelOut(MainTest.java:700)
12:22:51 [INFO ] 
12:22:51 [INFO ] [INFO] 
12:22:51 [INFO ] [INFO] Results:
12:22:51 [INFO ] [INFO] 
12:22:51 [INFO ] [ERROR] Failures: 
12:22:51 [INFO ] [ERROR]   MainTest.testParallelOut:700->run:966->run:1006 » ConcurrentModification
```

ping me on Slack, I'll add you to https://concord-ci.ibodrov.ca :-)

**Comment by ibodrov** [comment]
@concord-ci test it

**Comment by ibodrov** [comment]
Marking as `wip`. I want to take a look at the source of those `ConcurrentModificationException`.

**Comment by amithkb** [comment]
> Marking as `wip`. I want to take a look at the source of those `ConcurrentModificationException`.

@ibodrov `ConcurrentModificationException` occurred at [here](https://github.com/walmartlabs/concord/blob/fff7e94e15554ea7d3030f732fc420dd8808bcc5/runtime/v2/runner/src/test/java/com/walmartlabs/concord/runtime/v2/runner/MainTest.java#L1006) with [this](https://github.com/walmartlabs/concord/blob/master/runtime/v2/runner/src/test/resources/com/walmartlabs/concord/runtime/v2/runner/parallelOut/concord.yml) yaml which does not use `http-task`. Hence i think that this PR is not the source :)

**Review by ibodrov — APPROVED** [review]

**Pull request merged**
